version: "3"
services:
    cloudflared:
        container_name: cloudflared
        image: zoeyvid/cloudflared:latest
        restart: always
        network_mode: host
        environment:
        - "TZ=Europe/Berlin"
        - "token=your-cloudflared-tunnel-token"
#        entrypoint: cloudflared
#        command: --no-autoupdate --metrics localhost:9133 # command to execute after cloudflared --no-autoupdate --metrics localhost:9133 
