version: "3"
services:
    cloudflared:
        container_name: cloudflared
        image: sancraftdev/cloudflared:latest
#        image: sancraftdev/cloudflared:develop
        restart: always
        network_mode: host
        environment:
        - "TZ=Europe/Berlin"
        - "token=your-cloudflared-tunnel-token"
#        command: # command to execute after cloudflared --no-autoupdate
