name: dependency-updates

on:
  schedule:
    - cron:  "0 */6 * * *"
  workflow_dispatch:

jobs:
  dependency_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: update cloudflared version
        id: update
        run: |
          CLOUDFLARED_VERSION="$(
          git ls-remote --tags https://github.com/cloudflare/cloudflared \
              | cut -d/ -f3 \
              | sort -V \
              | tail -1 \
              | sed -E "s/\^\{\}//"
          )"
          sed -i "s|ARG CLOUDFLARED_VERSION=.*|ARG CLOUDFLARED_VERSION=$CLOUDFLARED_VERSION|" ./Dockerfile
          echo "version=$CLOUDFLARED_VERSION" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          signoff: true
          delete-branch: true
          commit-message: update cloudflared version to ${{ steps.update.outputs.version }}
          branch: update-cloudflared-version
          title: update cloudflared version to ${{ steps.update.outputs.version }}
          body: update cloudflared version to ${{ steps.update.outputs.version }}
          
#      - name: push
#        run: |
#          git config --global user.name "Gtihub Actions"
#          git config --global user.email "noreply@github.com"
#          git add Dockerfile
#          git commit -m "update cloudflared version" --signoff
#          git push
