name: dependency-updates

on:
  branch_protection_rule:
  check_run:
  check_suite:
  delete:
  discussion:
  discussion_comment:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  repository_dispatch:
  status:
  watch:
  workflow_run:
  
  push:
  schedule:
    - cron:  "0 */6 * * *"
  workflow_dispatch:

jobs:
  cloudflared-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: update cloudflared version
        id: update
        run: |
          CLOUDFLARED_VERSION="$(
          git ls-remote --tags https://github.com/cloudflare/cloudflared \
              | cut -d/ -f3 \
              | sort -V \
              | tail -1 \
              | sed -E "s/\^\{\}//"
          )"
          sed -i "s|ARG CLOUDFLARED_VERSION=.*|ARG CLOUDFLARED_VERSION=$CLOUDFLARED_VERSION|" ./Dockerfile
          echo "version=$CLOUDFLARED_VERSION" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          signoff: true
          delete-branch: true
          commit-message: update cloudflared version to ${{ steps.update.outputs.version }}
          branch: update-cloudflared-version
          title: update cloudflared version to ${{ steps.update.outputs.version }}
          body: update cloudflared version to ${{ steps.update.outputs.version }}
