name: dependency-updates

on:
  push:
  schedule:
    - cron:  "0 */6 * * *"
  workflow_dispatch:

jobs:
  cloudflared-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: update cloudflared version
        id: update
        run: |
          CLOUDFLARED_VERSION="$(
          git ls-remote --tags https://github.com/cloudflare/cloudflared \
              | cut -d/ -f3 \
              | sort -V \
              | tail -1 \
              | sed -E "s/\^\{\}//"
          )"
          sed -i "s|ARG CLOUDFLARED_VERSION=.*|ARG CLOUDFLARED_VERSION=$CLOUDFLARED_VERSION|" ./Dockerfile
          echo "version=$CLOUDFLARED_VERSION" >> $GITHUB_OUTPUT
          
      - name: push changes
        run: |
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git add -A
          git diff-index --quiet HEAD || bash -c "git commit -sm "update cloudflared version to ${{ steps.update.outputs.version }}" && git push && curl -X POST https://api.github.com/repos/ZoeyVid/cloudflared/dispatches --header "authorization: Bearer ${{ secrets.ACTION_RUN }}" --data '{"event_type": "docker"}'"
